# Generated by Django 5.1.2 on 2025-02-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("event_date_time", models.DateTimeField(auto_now_add=True)),
                ("environment", models.CharField(max_length=255)),
                ("event_context", models.JSONField()),
                ("metadata_version", models.BigIntegerField(default=1)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
